/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_iluafltk_h_
#define _su_iluafltk_h_




struct lua_State;


namespace su
{


	struct ILuaFltk : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x11ad8212u )


		virtual int    Lua_check           ( lua_State* L ) = 0;

		virtual int    Lua_wait            ( lua_State* L ) = 0;

		virtual int    Lua_flush           ( lua_State* L ) = 0;

		virtual int    Lua_redraw          ( lua_State* L ) = 0;

		virtual int    Lua_belowmouse      ( lua_State* L ) = 0;

		virtual int    Lua_focus           ( lua_State* L ) = 0;

		virtual int    Lua_screencount     ( lua_State* L ) = 0;

		virtual int    Lua_buildversion    ( lua_State* L ) = 0;

		virtual int    Lua_lock            ( lua_State* L ) = 0;

		virtual int    Lua_unlock          ( lua_State* L ) = 0;

		virtual int    Lua_xid             ( lua_State* L ) = 0;

		virtual int    Lua_find            ( lua_State* L ) = 0;

		virtual int    Lua_iswindow        ( lua_State* L ) = 0;

		virtual int    Lua_isgroup         ( lua_State* L ) = 0;

		virtual int    Lua_firstWindow     ( lua_State* L ) = 0;

		virtual int    Lua_nextWindow      ( lua_State* L ) = 0;

		virtual int    Lua_mousexy         ( lua_State* L ) = 0;

		virtual int    Lua_newImage        ( lua_State* L ) = 0;

		virtual int    Lua_imageId         ( lua_State* L ) = 0;

		virtual int    LuaImg_width        ( lua_State* L ) = 0;

		virtual int    LuaImg_height       ( lua_State* L ) = 0;

		virtual int    LuaImg_bpp          ( lua_State* L ) = 0;

		virtual int    LuaImg_gc           ( lua_State* L ) = 0;
	};


}




#endif // _su_iluafltk_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

