/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_idriverfs_h_
#define _su_idriverfs_h_




namespace su
{


	struct IDriverFS : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x85124ea8u )


		enum
		{
			A_NOT_FOUND = (0),
			A_FILE      = (1<<0),
			A_DIR       = (1<<1),
			A_WTIME     = (1<<2),
			A_CTIME     = (1<<3),
			A_ATIME     = (1<<4),
			A_RONLY     = (1<<5),
			A_HIDDEN    = (1<<6),
			A_SYSTEM    = (1<<7),
		};


		virtual uint            GetAttributes      ( pcstr   inFilename                  ) = 0;

		virtual uint            AndAttributes      ( pcstr   inFilename                 ,
		                                             uint    inAttributes                ) = 0;

		virtual uint            OrAttributes       ( pcstr   inFilename                 ,
		                                             uint    inAttributes                ) = 0;

		virtual bool            GetSize            ( pcstr   inFilename                 ,
		                                             uint64& outBSize                    ) = 0;

		virtual bool            GetWriteTime       ( pcstr   inFilename                 ,
		                                             Date&   outDate                     ) = 0;

		virtual bool            GetCreationTime    ( pcstr   inFilename                 ,
		                                             Date&   outDate                     ) = 0;

		virtual bool            CopyFile           ( pcstr   inDstFilename              ,
		                                             pcstr   inSrcFilename              ,
		                                             bool    inFailIfExists              ) = 0;

		virtual bool            MoveFile           ( pcstr   inDstFilename              ,
		                                             pcstr   inSrcFilename               ) = 0;

		virtual bool            CreateFile         ( pcstr   inFilename                 ,
		                                             bool    inFailIfExists      = FALSE,
		                                             uint64  inBSize             = 0     ) = 0;

		virtual bool            CreateDir          ( pcstr   inDirname                   ) = 0;

		virtual bool            RemoveFile         ( pcstr   inFilename                  ) = 0;

		virtual bool            RemoveDir          ( pcstr   inDirname                  ,
		                                             bool    inForceNotEmpty             ) = 0;

		virtual IFileView*      OpenView           ( pcstr   inFilename                 ,
		                                             Pool*   inPool                      ) = 0;

		virtual IFileBurst*     OpenBurst          ( pcstr   inFilename                 ,
		                                             Pool*   inPool                      ) = 0;

		virtual IFileReader*    OpenReader         ( pcstr   inFilename                 ,
		                                             Pool*   inPool                      ) = 0;

		virtual IFileWriter*    OpenWriter         ( pcstr   inFilename                 ,
		                                             Pool*   inPool                     ,
		                                             bool    inCreateIfNotExists = true ,
		                                             bool    inAppend            = true  ) = 0;

		virtual IDirectory*     OpenDir            ( pcstr   inDirname                  ,
		                                             Pool*   inPool                      ) = 0;

		virtual PString         GetHostPath        ( pcstr   inVirtualPath               ) = 0;
	};


}




#endif // _su_idriverfs_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

