/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_iluacore_h_
#define _su_iluacore_h_




struct lua_State;


namespace su
{


	struct ILuaCore : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x95d746f8u )


		virtual int    Lua_stdout             ( lua_State* L ) = 0;

		virtual int    Lua_stderr             ( lua_State* L ) = 0;

		virtual int    Lua_loadProfile        ( lua_State* L ) = 0;

		virtual int    Lua_update             ( lua_State* L ) = 0;

		virtual int    Lua_processEvent       ( lua_State* L ) = 0;

		virtual int    Lua_waitEvent          ( lua_State* L ) = 0;

		virtual int    Lua_setWaitInterval    ( lua_State* L ) = 0;

		virtual int    Lua_sleep              ( lua_State* L ) = 0;

		virtual int    Lua_buildLevel         ( lua_State* L ) = 0;

		virtual int    Lua_buildRevision      ( lua_State* L ) = 0;

		virtual int    Lua_buildPlatform      ( lua_State* L ) = 0;
	};


}




#endif // _su_iluacore_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

