/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_iluanet_h_
#define _su_iluanet_h_




struct lua_State;


namespace su
{


	struct ILuaNet : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x7c32d447u )


		virtual int    Lua_decomposeUrl     ( lua_State* L ) = 0;

		virtual int    Lua_newConnection    ( lua_State* L ) = 0;

		virtual int    LuaCo_setopt         ( lua_State* L ) = 0;

		virtual int    LuaCo_getopt         ( lua_State* L ) = 0;

		virtual int    LuaCo_delopt         ( lua_State* L ) = 0;

		virtual int    LuaCo_getstate       ( lua_State* L ) = 0;

		virtual int    LuaCo_connect        ( lua_State* L ) = 0;

		virtual int    LuaCo_disconnect     ( lua_State* L ) = 0;

		virtual int    LuaCo_receive        ( lua_State* L ) = 0;

		virtual int    LuaCo_send           ( lua_State* L ) = 0;

		virtual int    LuaCo_perform        ( lua_State* L ) = 0;

		virtual int    LuaCo_gc             ( lua_State* L ) = 0;
	};


}




#endif // _su_iluanet_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

