/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_ifile_h_
#define _su_ifile_h_




namespace su
{


	struct IFile : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x088fc99du )


		enum State
		{
			S_IDLE       = (0),
			S_PENDING    = (1),
			S_INPROGRESS = (2),
			S_COMPLETED  = (3),
			S_ABORTED    = (-1),
			S_FAILED     = (-2),
		};


		enum Error
		{
			E_SUCCESS    = (0),
			E_NO_DATA    = (1),
			E_WRONG_DISK = (2),
			E_NO_DISK    = (3),
			E_NO_DRIVE   = (4),
			E_FATAL      = (5),
			E_RETRY      = (6),
			E_UNDEFINED  = (7),
		};


		virtual uint64    GetSize         (  ) = 0;

		virtual State     GetState        (  ) = 0;

		virtual Error     GetLastError    (  ) = 0;

		virtual bool      IsReadable      (  ) = 0;

		virtual bool      IsWritable      (  ) = 0;

		virtual void      Flush           (  ) = 0;
	};


}




#endif // _su_ifile_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

