/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_ifileburst_h_
#define _su_ifileburst_h_




namespace su
{


	struct IFileBurst : public IFile
	{
		SU_DECL_INTERFACE( IFile, 0x8a09f698u )


		virtual bool    StartTransfer    ( void*   inBuffer         ,
		                                   uint64  inBSize          ,
		                                   uint64  inBOffset        ,
		                                   void*&  outAlignedBuffer ,
		                                   uint64& outAlignedBSize  ,
		                                   uint64& outAlignedBOffset ) = 0;

		virtual void    AbortTransfer    (                           ) = 0;
	};


}




#endif // _su_ifileburst_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

