/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_iluaio_h_
#define _su_iluaio_h_




struct lua_State;


namespace su
{


	struct ILuaIO : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0x4ec5ff65u )


		virtual int    Lua_isExists          ( lua_State* L ) = 0;

		virtual int    Lua_isEmpty           ( lua_State* L ) = 0;

		virtual int    Lua_isDirectory       ( lua_State* L ) = 0;

		virtual int    Lua_isFile            ( lua_State* L ) = 0;

		virtual int    Lua_isReadOnly        ( lua_State* L ) = 0;

		virtual int    Lua_isHidden          ( lua_State* L ) = 0;

		virtual int    Lua_isSystem          ( lua_State* L ) = 0;

		virtual int    Lua_isFullname        ( lua_State* L ) = 0;

		virtual int    Lua_findFile          ( lua_State* L ) = 0;

		virtual int    Lua_listDirectory     ( lua_State* L ) = 0;

		virtual int    Lua_splitExtension    ( lua_State* L ) = 0;

		virtual int    Lua_hasExtension      ( lua_State* L ) = 0;

		virtual int    Lua_getExtension      ( lua_State* L ) = 0;

		virtual int    Lua_getSize           ( lua_State* L ) = 0;

		virtual int    Lua_glob              ( lua_State* L ) = 0;

		virtual int    Lua_getDirname        ( lua_State* L ) = 0;

		virtual int    Lua_getBasename       ( lua_State* L ) = 0;

		virtual int    Lua_getFullname       ( lua_State* L ) = 0;

		virtual int    Lua_getNormalized     ( lua_State* L ) = 0;

		virtual int    Lua_getHostPath       ( lua_State* L ) = 0;

		virtual int    Lua_getVirtualPath    ( lua_State* L ) = 0;

		virtual int    Lua_hashContent       ( lua_State* L ) = 0;

		virtual int    Lua_removeFile        ( lua_State* L ) = 0;

		virtual int    Lua_removeDir         ( lua_State* L ) = 0;

		virtual int    Lua_parseStream       ( lua_State* L ) = 0;

		virtual int    Lua_loadStream        ( lua_State* L ) = 0;

		virtual int    Lua_presentStream     ( lua_State* L ) = 0;

		virtual int    Lua_dumpStream        ( lua_State* L ) = 0;

		virtual int    Lua_loadBinary        ( lua_State* L ) = 0;

		virtual int    Lua_dumpBinary        ( lua_State* L ) = 0;

		virtual int    Lua_mount             ( lua_State* L ) = 0;

		virtual int    Lua_unmount           ( lua_State* L ) = 0;

		virtual int    Lua_unmountAll        ( lua_State* L ) = 0;

		virtual int    Lua_listMount         ( lua_State* L ) = 0;
	};


}




#endif // _su_iluaio_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

