/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_iluastate_h_
#define _su_iluastate_h_




struct lua_State;


namespace su
{


	struct ILuaState : public IInterface
	{
		SU_DECL_INTERFACE( IInterface, 0xcd068edfu )


		struct Chunk;
		struct Error;


		enum Status
		{
			S_UNDEFINED = (0),
			S_RUNNING   = (1),
			S_YIELDED   = (2),
			S_FINISHED  = (3),
			S_ERRCHUNK  = (4),
			S_ERRSYNTAX = (5),
			S_ERRRUN    = (6),
			S_ERRMEM    = (7),
			S_ERRERR    = (8),
			S_ERRFATAL  = (9),
		};


		struct Chunk
		{
			byte* baddr;
			uint bsize;
			LString name;
			BString<2048> path;
		};


		struct Error
		{
			Status status;
			BString<2048> reason;
		};


		virtual bool          Realize               ( bool   inOptimizeCode = SU_BUILD_FASTCODE,
		                                              Pool*  inStatePool    = NULL              ) = 0;

		virtual bool          IsRealized            (                                         ) = 0;

		virtual void          Unrealize             (                                         ) = 0;

		virtual lua_State*    GetState              (                                         ) = 0;

		virtual Pool*         GetStatePool          (                                         ) = 0;

		virtual void          GarbageCollect        (                                         ) = 0;

		virtual bool          RunTask               ( Chunk& inChunk                           ,
		                                              Error* outError       = NULL              ) = 0;

		virtual int           StartCoroutine        ( Chunk& inChunk                           ,
		                                              Error* outError       = NULL              ) = 0;

		virtual Status        GetCoroutineStatus    ( int    inCoid                             ) = 0;

		virtual bool          ResumeCoroutine       ( int    inCoid                            ,
		                                              Error* outError       = NULL              ) = 0;

		virtual void          RecycleCoroutine      ( int    inCoid                             ) = 0;
	};


}




#endif // _su_iluastate_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

