/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


//==== includes ====================================================================================

#include <sufw/precompiled/supch_core.h>
#include "..\base\su_iconsole.h"
#include <stdarg.h>




//==== defines =====================================================================================

#ifndef SIDL_IMPL_CLASSNAME
#define SIDL_IMPL_CLASSNAME MFileConsole
#endif

#ifndef SIDL_IMPL_MUID
#define SIDL_IMPL_MUID 0x44ba5dffu
#endif

#ifndef SIDL_IMPL_REVISION
#define SIDL_IMPL_REVISION 0
#endif

#ifndef SIDL_IMPL_PACKAGE
#define SIDL_IMPL_PACKAGE "su.fw.core"
#endif

#ifndef SIDL_IMPL_ATTR_V
#define SIDL_IMPL_ATTR_V NULL
#endif

#ifndef SIDL_IMPL_ATTR_C
#define SIDL_IMPL_ATTR_C 0
#endif

#ifndef SIDL_STUB_CLASSNAME
#define SIDL_STUB_CLASSNAME MFileConsole_Stub
#endif

#ifndef SIDL_IMPL_INTERFACE
#define SIDL_IMPL_INTERFACE(I) ((I*)MFileConsole_get_interface(MFileConsole_stub_to_base(this),I::ClassId))
#endif


//==== declarations ================================================================================

namespace {

su::IInterface* MFileConsole_create_object( su::Pool*, su::Pool*, su::AnyList* );
void* MFileConsole_base_to_stub ( void* );
void* MFileConsole_stub_to_base ( void* );
su::addin::Builder* MFileConsole_builder ( );
uint MFileConsole_count_interface ( );
bool MFileConsole_enum_interface ( uint, su::classid*, pcstr* );
su::IInterface* MFileConsole_first_interface ( void* );
su::IInterface* MFileConsole_get_interface ( void*, su::classid );

}


//==== stub area ===================================================================================

#undef  SIDL_PROPER
#undef  SIDL_STUB
#undef  SIDL_BUILDER
#undef  SIDL_CODE
#define SIDL_STUB
#include "su_mfileconsole_stub.h"




//==== skeleton ====================================================================================

namespace {


struct MFileConsole
{

//---- bridges -------------------------------------------------------------------------------------

struct IConsole_t : public su::IConsole {
	// from IInterface
	::su::classbase         GetBase        (  ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return &(*m); }
	::su::addin::Builder *  GetBuilder     (  ) { return MFileConsole_builder(); }
	void                    Retain         (  ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); (*m).Retain(); }
	::uint                  CountRef       (  ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (*m).CountRef(); }
	void                    Release        (  ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); (*m).Release(); }
	::uint                  CountInterface (  ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (*m).CountInterface(); }
	bool                    EnumInterface  ( ::uint p0,::su::classid * p1,::pcstr * p2 ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (*m).EnumInterface(p0,p1,p2); }
	::su::IInterface *      GetInterface   ( ::su::classid p0 ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (*m).GetInterface(p0); }
	// from IConsole
	::su::IConsole::Action  AskUserAction  ( ::pcstr p0,::pcstr p1,::pcstr p2,int p3 ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (m->stub).AskUserAction(p0,p1,p2,p3); }
	bool                    Output         ( ::pcstr p0,::pcstr p1,::pcstr p2,int p3 ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (m->stub).Output(p0,p1,p2,p3); }
	bool                    Input          ( char & p0 ) { MFileConsole* m = SU_DELEGATE_BASEPTR(MFileConsole,IConsole_i,this); return (m->stub).Input(p0); }
} IConsole_i;


//---- stub nested object --------------------------------------------------------------------------

MFileConsole_Stub stub;


//---- skeleton management code area ---------------------------------------------------------------

int refcount;
Pool* nestp;


void Retain ( )
{
	refcount++;
}


uint CountRef ( )
{
	return refcount;
}


void Release ( )
{
	if( refcount==1 )
		Destroy( this );
	else
		refcount--;
}


uint CountInterface ( )
{
	return MFileConsole_count_interface();
}


bool EnumInterface ( uint i, su::classid* cid, pcstr* cname )
{
	return MFileConsole_enum_interface(i,cid,cname);
}


su::IInterface* GetInterface ( classid cid )
{
	SU_IMPLEMENTS_MEMBER( IConsole_i, cid );
	return NULL;
}


static MFileConsole* Create( Pool* np, Pool* dp, AnyList* o )
{
	if( !np )	return NULL;
	MFileConsole* m = np->New<MFileConsole>();
	if( !m )	return NULL;
	m->refcount = 1;
	m->nestp = np;
	if( !m->stub.Init(dp,o) )
	{
		np->Delete( m );
		return NULL;
	}
	return m;
}


static void Destroy( MFileConsole* m )
{
	m->stub.Shut();
	m->refcount=0;
	m->nestp->Delete( m );
}

};

}




//==== builder =====================================================================================


SU_BEGIN_BUILDER( MFileConsole )

su::classid GetMUID ( ) { return SIDL_IMPL_MUID; }
pcstr GetMClassname ( ) { return "MFileConsole"; }
uint32 GetRevision ( ) { return SIDL_IMPL_REVISION; }
pcstr GetPackage ( ) { return SIDL_IMPL_PACKAGE; }
uint CountInterface ( ) { return MFileConsole_count_interface(); }
bool EnumInterface ( uint i, su::classid* cid, pcstr* cname ) { return MFileConsole_enum_interface(i,cid,cname); }
su::IInterface* FirstInterface ( void* base ) { return MFileConsole_first_interface(base); }
su::IInterface* GetInterface ( void* base, su::classid cid ) { return MFileConsole_get_interface(base,cid); }
su::IInterface* CreateObject( su::Pool* nestp, su::Pool* datap, su::AnyList* opts ) { return MFileConsole_create_object(nestp,datap,opts); }
void* BaseToStub ( void* base ) { return MFileConsole_base_to_stub(base); }
void* StubToBase ( void* base ) { return MFileConsole_stub_to_base(base); }
uint CountSwitch ( ) { return 0; }
bool EnumSwitch ( uint, su::ISwitch::Desc& ) { return false; }

SU_END_BUILDER( MFileConsole )




//==== definitions =================================================================================


namespace {


su::IInterface* MFileConsole_create_object( su::Pool* nestp, su::Pool* datap, su::AnyList* opts )
{
	MFileConsole* m = MFileConsole::Create( nestp, datap, opts );
	SU_REQUIRE_OR_NULL( m );
	return &m->IConsole_i;
}


void* MFileConsole_base_to_stub ( void* base )
{
	SU_REQUIRE_OR_NULL( base );
	return &(((MFileConsole*)base)->stub);
}


void* MFileConsole_stub_to_base ( void* stubp )
{
	SU_REQUIRE_OR_NULL( stubp );
	return SU_DELEGATE_BASEPTR(MFileConsole,stub,stubp);
}


su::addin::Builder* MFileConsole_builder ( )
{
	return &_builder_MFileConsole;
}


uint MFileConsole_count_interface ( )
{
	return 1;
}


bool MFileConsole_enum_interface ( uint i, su::classid* cid, pcstr* cname )
{
	static const su::classid cids[] = { su::IConsole::ClassId };
	static const pcstr cnames[] = { "IConsole" };
	SU_REQUIRE_OR_FALSE( i<1 );
	if( cid )   *cid   = cids[i];
	if( cname ) *cname = cnames[i];
	return true;
}


su::IInterface* MFileConsole_first_interface ( void* base )
{
	SU_REQUIRE_OR_NULL( base );
	return &(((MFileConsole*)base)->IConsole_i);
}


su::IInterface* MFileConsole_get_interface ( void* base, su::classid cid )
{
	SU_REQUIRE_OR_NULL( base );
	return ((MFileConsole*)base)->GetInterface(cid);
}


}


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

