/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


//==== includes ====================================================================================

#include <sufw/precompiled/supch_core.h>
#include "..\..\core\base\su_iinterface.h"
#include "su_iluacore.h"
#include "..\..\core\base\su_iswitch.h"
#include <stdarg.h>




//==== defines =====================================================================================

#ifndef SIDL_IMPL_CLASSNAME
#define SIDL_IMPL_CLASSNAME MLuaCore
#endif

#ifndef SIDL_IMPL_MUID
#define SIDL_IMPL_MUID 0x119d4802u
#endif

#ifndef SIDL_IMPL_QUALIFIER
#define SIDL_IMPL_QUALIFIER static
#endif

#ifndef SIDL_IMPL_IS_STATIC
#define SIDL_IMPL_IS_STATIC 
#endif

#ifndef SIDL_IMPL_SWITCHED
#define SIDL_IMPL_SWITCHED 
#endif

#ifndef SIDL_IMPL_REVISION
#define SIDL_IMPL_REVISION 0
#endif

#ifndef SIDL_IMPL_PACKAGE
#define SIDL_IMPL_PACKAGE "su.fw.lang"
#endif

#ifndef SIDL_IMPL_ATTR_V
#define SIDL_IMPL_ATTR_V NULL
#endif

#ifndef SIDL_IMPL_ATTR_C
#define SIDL_IMPL_ATTR_C 0
#endif

#ifndef SIDL_STUB_CLASSNAME
#define SIDL_STUB_CLASSNAME MLuaCore_Stub
#endif

#ifndef SIDL_IMPL_INTERFACE
#define SIDL_IMPL_INTERFACE(I) ((I*)MLuaCore_get_interface(MLuaCore_stub_to_base(this),I::ClassId))
#endif


//==== declarations ================================================================================

namespace {

su::IInterface* MLuaCore_create_object( su::Pool*, su::Pool*, su::AnyList* );
void* MLuaCore_base_to_stub ( void* );
void* MLuaCore_stub_to_base ( void* );
su::addin::Builder* MLuaCore_builder ( );
uint MLuaCore_count_interface ( );
bool MLuaCore_enum_interface ( uint, su::classid*, pcstr* );
su::IInterface* MLuaCore_first_interface ( void* );
su::IInterface* MLuaCore_get_interface ( void*, su::classid );
uint MLuaCore_count_switch ( );
bool MLuaCore_enum_switch ( uint, su::ISwitch::Desc& );
int MLuaCore_find_switch ( pcstr );
bool MLuaCore_call_switch_stack ( void*, uint, void*, va_list );
bool MLuaCore_call_switch_mem ( void*, uint, su::Any*, int, su::Any* );

}


//==== stub area ===================================================================================

#undef  SIDL_PROPER
#undef  SIDL_STUB
#undef  SIDL_BUILDER
#undef  SIDL_CODE
#define SIDL_STUB
#include "su_mluacore_stub.h"




//==== skeleton ====================================================================================

namespace {


struct MLuaCore
{

//---- bridges -------------------------------------------------------------------------------------

struct ILuaCore_t : public su::ILuaCore {
	// from IInterface
	::su::classbase         GetBase             (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return &(*m); }
	::su::addin::Builder *  GetBuilder          (  ) { return MLuaCore_builder(); }
	void                    Retain              (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); (*m).Retain(); }
	::uint                  CountRef            (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (*m).CountRef(); }
	void                    Release             (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); (*m).Release(); }
	::uint                  CountInterface      (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (*m).CountInterface(); }
	bool                    EnumInterface       ( ::uint p0,::su::classid * p1,::pcstr * p2 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (*m).EnumInterface(p0,p1,p2); }
	::su::IInterface *      GetInterface        ( ::su::classid p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (*m).GetInterface(p0); }
	// from ILuaCore
	int                     Lua_stdout          ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_stdout(p0); }
	int                     Lua_stderr          ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_stderr(p0); }
	int                     Lua_loadProfile     ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_loadProfile(p0); }
	int                     Lua_update          ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_update(p0); }
	int                     Lua_processEvent    ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_processEvent(p0); }
	int                     Lua_waitEvent       ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_waitEvent(p0); }
	int                     Lua_setWaitInterval ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_setWaitInterval(p0); }
	int                     Lua_sleep           ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_sleep(p0); }
	int                     Lua_buildLevel      ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_buildLevel(p0); }
	int                     Lua_buildRevision   ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_buildRevision(p0); }
	int                     Lua_buildPlatform   ( lua_State* p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ILuaCore_i,this); return (m->stub).Lua_buildPlatform(p0); }
} ILuaCore_i;


struct ISwitch_t : public su::ISwitch {
	// from IInterface
	::su::classbase         GetBase        (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return &(*m); }
	::su::addin::Builder *  GetBuilder     (  ) { return MLuaCore_builder(); }
	void                    Retain         (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); (*m).Retain(); }
	::uint                  CountRef       (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return (*m).CountRef(); }
	void                    Release        (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); (*m).Release(); }
	::uint                  CountInterface (  ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return (*m).CountInterface(); }
	bool                    EnumInterface  ( ::uint p0,::su::classid * p1,::pcstr * p2 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return (*m).EnumInterface(p0,p1,p2); }
	::su::IInterface *      GetInterface   ( ::su::classid p0 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return (*m).GetInterface(p0); }
	// from ISwitch
	::uint                  CountSwitch    (  ) { return MLuaCore_count_switch(); }
	bool                    EnumSwitch     ( ::uint p0,::su::ISwitch::Desc & p1 ) { return MLuaCore_enum_switch(p0,p1); }
	int                     FindSwitch     ( ::pcstr p0 ) { return MLuaCore_find_switch(p0); }
	bool                    CallSwitch     ( ::uint p0,void * p1,... ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); va_list vl; va_start(vl,p1); return MLuaCore_call_switch_stack(m,p0,p1,vl); va_end(vl); }
	bool                    CallSwitchMem  ( ::uint p0,::su::Any * p1,int p2,::su::Any * p3 ) { MLuaCore* m = SU_DELEGATE_BASEPTR(MLuaCore,ISwitch_i,this); return MLuaCore_call_switch_mem(m,p0,p1,p2,p3); }
} ISwitch_i;


//---- stub nested object --------------------------------------------------------------------------

MLuaCore_Stub stub;


//---- skeleton management code area ---------------------------------------------------------------

int refcount;


void Retain ( )
{
	refcount++;
}


uint CountRef ( )
{
	return refcount;
}


void Release ( )
{
	if( refcount==1 )
		Destroy( this );
	else
		refcount--;
}


uint CountInterface ( )
{
	return MLuaCore_count_interface();
}


bool EnumInterface ( uint i, su::classid* cid, pcstr* cname )
{
	return MLuaCore_enum_interface(i,cid,cname);
}


su::IInterface* GetInterface ( classid cid )
{
	SU_IMPLEMENTS_MEMBER( ILuaCore_i, cid );
	SU_IMPLEMENTS_MEMBER( ISwitch_i, cid );
	return NULL;
}


static MLuaCore* Create( Pool* np, Pool* dp, AnyList* o )
{
	static MLuaCore m;
	static bool yet = false;
	if( !yet )
	{
		m.refcount = 0;
		yet = true;
	}
	if( m.refcount==0 )
	{
		if( !m.stub.Init(dp,o) )
			return NULL;
	}
	m.refcount += 1;
	return &m;
}


static void Destroy( MLuaCore* m )
{
	m->stub.Shut();
	m->refcount=0;
}

};

}




//==== builder =====================================================================================


SU_BEGIN_BUILDER( MLuaCore )

su::classid GetMUID ( ) { return SIDL_IMPL_MUID; }
pcstr GetMClassname ( ) { return "MLuaCore"; }
uint32 GetRevision ( ) { return SIDL_IMPL_REVISION; }
pcstr GetPackage ( ) { return SIDL_IMPL_PACKAGE; }
uint CountInterface ( ) { return MLuaCore_count_interface(); }
bool EnumInterface ( uint i, su::classid* cid, pcstr* cname ) { return MLuaCore_enum_interface(i,cid,cname); }
su::IInterface* FirstInterface ( void* base ) { return MLuaCore_first_interface(base); }
su::IInterface* GetInterface ( void* base, su::classid cid ) { return MLuaCore_get_interface(base,cid); }
su::IInterface* CreateObject( su::Pool* nestp, su::Pool* datap, su::AnyList* opts ) { return MLuaCore_create_object(nestp,datap,opts); }
void* BaseToStub ( void* base ) { return MLuaCore_base_to_stub(base); }
void* StubToBase ( void* base ) { return MLuaCore_stub_to_base(base); }
uint CountSwitch ( ) { return MLuaCore_count_switch(); }
bool EnumSwitch ( uint i, su::ISwitch::Desc& desc ) { return MLuaCore_enum_switch(i,desc); }

SU_END_BUILDER( MLuaCore )




//==== definitions =================================================================================


namespace {


su::IInterface* MLuaCore_create_object( su::Pool* nestp, su::Pool* datap, su::AnyList* opts )
{
	MLuaCore* m = MLuaCore::Create( nestp, datap, opts );
	SU_REQUIRE_OR_NULL( m );
	return &m->ILuaCore_i;
}


void* MLuaCore_base_to_stub ( void* base )
{
	SU_REQUIRE_OR_NULL( base );
	return &(((MLuaCore*)base)->stub);
}


void* MLuaCore_stub_to_base ( void* stubp )
{
	SU_REQUIRE_OR_NULL( stubp );
	return SU_DELEGATE_BASEPTR(MLuaCore,stub,stubp);
}


su::addin::Builder* MLuaCore_builder ( )
{
	return &_builder_MLuaCore;
}


uint MLuaCore_count_interface ( )
{
	return 2;
}


bool MLuaCore_enum_interface ( uint i, su::classid* cid, pcstr* cname )
{
	static const su::classid cids[] = { su::ILuaCore::ClassId, su::ISwitch::ClassId };
	static const pcstr cnames[] = { "ILuaCore", "ISwitch" };
	SU_REQUIRE_OR_FALSE( i<2 );
	if( cid )   *cid   = cids[i];
	if( cname ) *cname = cnames[i];
	return true;
}


su::IInterface* MLuaCore_first_interface ( void* base )
{
	SU_REQUIRE_OR_NULL( base );
	return &(((MLuaCore*)base)->ILuaCore_i);
}


su::IInterface* MLuaCore_get_interface ( void* base, su::classid cid )
{
	SU_REQUIRE_OR_NULL( base );
	return ((MLuaCore*)base)->GetInterface(cid);
}


uint MLuaCore_count_switch ( )
{
	return 11;
}


bool MLuaCore_enum_switch ( uint i, su::ISwitch::Desc& desc )
{
	static su::ISwitch::Desc swdesc[] = {
		{ "stdout", "Lua_stdout", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "stderr", "Lua_stderr", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "loadProfile", "Lua_loadProfile", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "update", "Lua_update", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "processEvent", "Lua_processEvent", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "waitEvent", "Lua_waitEvent", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "setWaitInterval", "Lua_setWaitInterval", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "sleep", "Lua_sleep", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "buildLevel", "Lua_buildLevel", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "buildRevision", "Lua_buildRevision", "int,lua_State*", "wp", "ILuaCore", NULL },
		{ "buildPlatform", "Lua_buildPlatform", "int,lua_State*", "wp", "ILuaCore", NULL },
		};
	SU_REQUIRE_OR_FALSE( i<11 );
	desc = swdesc[i];
	return true;
}


int MLuaCore_find_switch ( pcstr inname=NULL )
{
	SU_REQUIRE_OR_NEG( inname && inname[0] );
	for( uint i=0 ; i<11 ; i++ ) {
		su::ISwitch::Desc d; MLuaCore_enum_switch(i,d);
		if( util::Strequals(inname,d.name,false) )
			return i;
		}
	return -1;
}


bool MLuaCore_call_switch_stack ( void* base, uint i, void* r, va_list args )
{
	SU_REQUIRE_OR_FALSE( base );
	SU_REQUIRE_OR_FALSE( i<11 );
	if( i==0 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_stdout(p0);
		return true;
	}
	if( i==1 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_stderr(p0);
		return true;
	}
	if( i==2 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_loadProfile(p0);
		return true;
	}
	if( i==3 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_update(p0);
		return true;
	}
	if( i==4 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_processEvent(p0);
		return true;
	}
	if( i==5 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_waitEvent(p0);
		return true;
	}
	if( i==6 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_setWaitInterval(p0);
		return true;
	}
	if( i==7 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_sleep(p0);
		return true;
	}
	if( i==8 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_buildLevel(p0);
		return true;
	}
	if( i==9 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_buildRevision(p0);
		return true;
	}
	if( i==10 ) {
		SU_ASSERT( r );
		lua_State* p0 = va_arg(args,lua_State*);
		*((int*)r) = ((MLuaCore*)base)->ILuaCore_i.Lua_buildPlatform(p0);
		return true;
	}
	return false;
}


bool MLuaCore_call_switch_mem ( void* base, uint i, Any* r, int argc, Any* argv )
{
	SU_REQUIRE_OR_FALSE( base );
	SU_REQUIRE_OR_FALSE( i<11 );
	if( i==0 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_stdout(p0) );
		return true;
	}
	if( i==1 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_stderr(p0) );
		return true;
	}
	if( i==2 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_loadProfile(p0) );
		return true;
	}
	if( i==3 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_update(p0) );
		return true;
	}
	if( i==4 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_processEvent(p0) );
		return true;
	}
	if( i==5 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_waitEvent(p0) );
		return true;
	}
	if( i==6 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_setWaitInterval(p0) );
		return true;
	}
	if( i==7 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_sleep(p0) );
		return true;
	}
	if( i==8 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_buildLevel(p0) );
		return true;
	}
	if( i==9 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_buildRevision(p0) );
		return true;
	}
	if( i==10 ) {
		SU_ASSERT( argc==1 && argv )
		SU_ASSERT( r )
		lua_State* p0 = (lua_State*)argv[0].asPointer();
		r->set( ((MLuaCore*)base)->ILuaCore_i.Lua_buildPlatform(p0) );
		return true;
	}
	return false;
}


}


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.

