/*LIC-HDR********************************************************************
**
** Copyright (C) 2005-2011 AtOnce Technologies
**
** This file is part of the Sugar core-system framework.
**
** This file and the associated product may be used and distributed
** under the terms of a current License as defined by AtOnce Technologies
** and appearing in the file LICENSE.TXT included in the packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
** See http://www.atonce-technologies.com or email info@atonce-technologies.com
** for informations about Sugar Framework and AtOnce Technologies others products
** License Agreements.
**
** Contact info@atonce-technologies.com if any conditions of this license
** are not clear to you.
**
*****************************************************************LIC-HDR*/


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


#ifndef _su_uids_h_
#define _su_uids_h_



namespace su { namespace uid
{

	const su::classid IAllocator = 0xee91dbf1u;
	const su::classid IAllocatorChunk = 0xda7ff84eu;
	const su::classid IAllocatorHeap = 0x1b521062u;
	const su::classid IAllocatorObstack = 0x7d57da64u;
	const su::classid IAssetDatabase = 0xc9999314u;
	const su::classid IAuthAssetBrowser = 0x34d4c3ddu;
	const su::classid IAuthBitmap = 0x80e0008au;
	const su::classid IAuthDbgMaster = 0xbac4e429u;
	const su::classid IAuthDummy = 0x1f192ccdu;
	const su::classid IAuthFacade = 0xff7f8fb1u;
	const su::classid IAuthGraphics = 0x212e2f68u;
	const su::classid IAuthObserver = 0x7a88d7d7u;
	const su::classid IBitmapDocument = 0xab6616cau;
	const su::classid ICameraGrabber = 0xa6189571u;
	const su::classid ICodec = 0x50f91e83u;
	const su::classid IConsole = 0xc7dae87du;
	const su::classid IDatatree = 0x89f04444u;
	const su::classid IDatatreeHeap = 0x6881ff1au;
	const su::classid IDatatreeIO = 0x63a53ccau;
	const su::classid IDirectApp = 0x24e2fdabu;
	const su::classid IDirectDraw = 0x01aeb40bu;
	const su::classid IDirectDrawDX9 = 0x1827a9e9u;
	const su::classid IDirectDrawGL = 0xae736976u;
	const su::classid IDirectInput = 0xe45a8a0fu;
	const su::classid IDirectShader = 0x4ca996beu;
	const su::classid IDirectSound = 0xc4fc7b5cu;
	const su::classid IDirectViewer = 0xb006a4c3u;
	const su::classid IDirectory = 0x65960a87u;
	const su::classid IDriver = 0x1ca3f528u;
	const su::classid IDriverFS = 0x85124ea8u;
	const su::classid IEffectDocument = 0xea227a28u;
	const su::classid IFile = 0x088fc99du;
	const su::classid IFileBurst = 0x8a09f698u;
	const su::classid IFileReader = 0xc2133658u;
	const su::classid IFileSystem = 0xc761aeefu;
	const su::classid IFileView = 0xabfcde3au;
	const su::classid IFileWriter = 0x998c67e6u;
	const su::classid IImageAnalyzer = 0x22640095u;
	const su::classid IInterface = 0x171aa280u;
	const su::classid ILuaCore = 0x95d746f8u;
	const su::classid ILuaDatatree = 0x81517fd8u;
	const su::classid ILuaFltk = 0x11ad8212u;
	const su::classid ILuaGraphic = 0x416513acu;
	const su::classid ILuaIO = 0x4ec5ff65u;
	const su::classid ILuaLang = 0xcf5347d5u;
	const su::classid ILuaMath = 0x577dc7fau;
	const su::classid ILuaNet = 0x7c32d447u;
	const su::classid ILuaState = 0xcd068edfu;
	const su::classid ILuaString = 0x99bde3ecu;
	const su::classid ILuaUtil = 0x203c7114u;
	const su::classid ILuaWindows = 0xde38131du;
	const su::classid IModelDocument = 0xdbde37ebu;
	const su::classid IMutex = 0x462e7d85u;
	const su::classid INull = 0xa1db03c2u;
	const su::classid IPakDesigner = 0x93affa10u;
	const su::classid IRscManager = 0xcfa37c93u;
	const su::classid ISema = 0x7824620cu;
	const su::classid ISignal = 0x79c91c04u;
	const su::classid IStateMachine = 0x3e79b516u;
	const su::classid ISuaStream = 0x849362f9u;
	const su::classid ISwfReader = 0x3fc76c2au;
	const su::classid ISwitch = 0x622cc2e9u;
	const su::classid ISwitchUser = 0x18d71cbbu;
	const su::classid IThread = 0x3ce5c572u;
	const su::classid IThreadRef = 0xb350f5d7u;
	const su::classid ITimer = 0xc23311b0u;
	const su::classid IUICanvas = 0xbcc866c7u;
	const su::classid IUICollection = 0x28e9c7ccu;
	const su::classid IUIObject = 0xb1faa133u;
	const su::classid MAllocatorChunk = 0x50039d2du;
	const su::classid MAllocatorHeap = 0x02fe9f79u;
	const su::classid MAllocatorInner = 0xa834e7cau;
	const su::classid MAllocatorObstack = 0x0e5ffdabu;
	const su::classid MAllocatorOuter = 0xb1dde452u;
	const su::classid MAllocatorSlab = 0x798e0520u;
	const su::classid MAllocatorStd = 0xafa698bbu;
	const su::classid MAssetDatabase = 0xd0351c0fu;
	const su::classid MAssetViewer = 0x2fa23dfbu;
	const su::classid MAuthBitmap = 0x30397308u;
	const su::classid MAuthDummy = 0x16f28cb7u;
	const su::classid MAuthGraphics = 0xe19745feu;
	const su::classid MBitmapDocument = 0x211a73a9u;
	const su::classid MCameraGrabberDShow = 0x03a2de91u;
	const su::classid MCodecGFL = 0xfd62268du;
	const su::classid MCodecJPEG = 0x924d1a53u;
	const su::classid MCodecLZH5 = 0xb114ae04u;
	const su::classid MCodecLZO = 0x8e49c58bu;
	const su::classid MCodecPNG = 0xbb00c0f8u;
	const su::classid MCodecPVRTC = 0xb89a966bu;
	const su::classid MCodecRS = 0x55dd858fu;
	const su::classid MCodecTGA = 0x84a87658u;
	const su::classid MCodecYM = 0x4c266127u;
	const su::classid MCodecZLIB = 0x0bb7ac5bu;
	const su::classid MConsoleNet = 0x781c9d1du;
	const su::classid MConsoleStd = 0x228c9e4au;
	const su::classid MDatatreeHeap = 0xa838958cu;
	const su::classid MDatatreeIO = 0xd37c4f48u;
	const su::classid MDirectApp = 0x2d095dd1u;
	const su::classid MDirectDrawDX9 = 0x018b26f2u;
	const su::classid MDirectDrawGL = 0x6eca03e0u;
	const su::classid MDirectShaderBaseDX9 = 0x5a1c3523u;
	const su::classid MDirectShaderBaseGL = 0x2777cf5fu;
	const su::classid MDirectShaderCamera = 0x15e9a6ffu;
	const su::classid MDirectShaderPrimDX9 = 0xc0fb6f3du;
	const su::classid MDirectShaderPrimGL = 0x7f9e67deu;
	const su::classid MDirectShaderProgramDX9 = 0x7f31fcd2u;
	const su::classid MDirectShaderProgramGL = 0x656c9eedu;
	const su::classid MDirectShaderTileDX9 = 0x50f11ee9u;
	const su::classid MDirectShaderTileGL = 0xcaf222d1u;
	const su::classid MDirectSoundDX9 = 0x32af0f23u;
	const su::classid MDirectViewer = 0x70bfce55u;
	const su::classid MDirectory = 0x6c7daafdu;
	const su::classid MDriverFS = 0xd8fe1fa4u;
	const su::classid MFbxDocument = 0xc3595e7du;
	const su::classid MFileBurst = 0x83e256e2u;
	const su::classid MFileConsole = 0x44ba5dffu;
	const su::classid MFileReader = 0x72ca45dau;
	const su::classid MFileSystem = 0x77b8dd6du;
	const su::classid MFileView = 0xf6108f36u;
	const su::classid MFileWriter = 0x29551464u;
	const su::classid MFlAssetBrowser = 0x5a80765au;
	const su::classid MFlConsole = 0xcf5ea79bu;
	const su::classid MFlConsoleView = 0x51fdc481u;
	const su::classid MFlDesigner = 0xcde8ff8eu;
	const su::classid MFlLayoutManager = 0x19d5a73eu;
	const su::classid MFlLuaDbgMaster = 0x37cb6097u;
	const su::classid MFlLuaDbgViewer = 0x199e6f14u;
	const su::classid MFlNetworkViewer = 0x26848b57u;
	const su::classid MFlSessionChooser = 0x93b9ceffu;
	const su::classid MFlUserDataInspector = 0x2516ec62u;
	const su::classid MFlWorldInspector = 0xe798ecb4u;
	const su::classid MFxDocument = 0x570db8deu;
	const su::classid MImageAnalyzer = 0x3bc88f8eu;
	const su::classid MLuaAuthFacade = 0x8a2c2439u;
	const su::classid MLuaCore = 0x119d4802u;
	const su::classid MLuaDatatree = 0x825744a7u;
	const su::classid MLuaFltk = 0x95e78ce8u;
	const su::classid MLuaGraphic = 0xf1bc602eu;
	const su::classid MLuaIO = 0xd554bd73u;
	const su::classid MLuaLang = 0x4b19492fu;
	const su::classid MLuaMath = 0xd337c900u;
	const su::classid MLuaNet = 0x887df054u;
	const su::classid MLuaState = 0x90eadfd3u;
	const su::classid MLuaString = 0x90564396u;
	const su::classid MLuaUtil = 0xa4767feeu;
	const su::classid MLuaWindows = 0x6ee1609fu;
	const su::classid MNull = 0x545ba502u;
	const su::classid MNullConsole = 0xdca4c6f7u;
	const su::classid MObjDocument = 0x3a220a0fu;
	const su::classid MPakDesigner = 0x90a9c16fu;
	const su::classid MRscManager = 0x7f7a0f11u;
	const su::classid MSwfReader = 0x362ccc50u;
	const su::classid NotSupported = 0x0227b8dfu;

	const su::classid MAllocatorPool = MAllocatorStd;
	const su::classid MCameraGrabber = MCameraGrabberDShow;
	const su::classid MCodecCocoa = NotSupported;
	const su::classid MDirectDraw = MDirectDrawDX9;
	const su::classid MDirectSound = MDirectSoundDX9;

} }




#endif // _su_uids_h_


// !! This file has been automatically generated by the sugar sidl tool.
// !! Do not edit this file manually under risk of losing your changes.


